version: 2.0

jobs:
  "bbbase-ci":
    machine: true
    # working_directory: ~/
    steps:
      - run: uname -a
      - run: make --version
      - run: pwd
      - checkout
      - run: git log -1
      - run: ls -lah
      - run:
          name: make
          command: make
workflows:
  version: 2
  build:
    jobs:
      - "bbbase-ci"

